apiVersion: v1
kind: Pod
metadata:
  name: data-generator
  namespace: sample-data
spec:
  containers:
  - name: writer
    image: busybox
    command: [ "/bin/sh", "-c" ]
    args:
    - |
      cat /dev/urandom | tr -dc 'A-Za-z0-9!@#$%^&*()_+-=[]{}|;:,.<>?' | head -c 500000000 > /data/random_printable.txt && \
      sleep 3600
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: sample-pvc
